# Generated by Django 5.0.1 on 2024-01-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studentmodelregistration_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query_Email', models.EmailField(max_length=254)),
                ('Query_Sub', models.CharField(max_length=300)),
                ('QueryDate', models.DateTimeField()),
                ('Query_Query', models.CharField(max_length=1000)),
            ],
        ),
    ]
